CREATE TABLE DEVICE_AUTHORIZATION(id VARCHAR(64) PRIMARY KEY, device_id VARCHAR(16) NOT NULL, authorizer VARCHAR(16) NOT NULL, authorized_time TIMESTAMP NOT NULL, expired_time TIMESTAMP NOT NULL, canceled BOOLEAN DEFAULT FALSE NOT NULL);
CREATE TABLE DEVICE_IDENTITY(id VARCHAR(64) PRIMARY KEY, device_id VARCHAR(16) NOT NULL, jid VARCHAR(32) NOT NULL, credentials VARCHAR(32) NOT NULL, authorization_id VARCHAR(64) NOT NULL, registered_time TIMESTAMP NOT NULL);
CREATE INDEX INDEX_DEVICE_ID ON DEVICE_IDENTITY (device_id);
CREATE INDEX INDEX_JID ON DEVICE_IDENTITY (jid);
