CREATE TABLE DEVICE_AUTHORZATION(id VARCHAR(64) PRIMARY KEY, device_id VARCHAR(16) NOT NULL, authorizer VARCHAR(16) NOT NULL, authorize_time DATE NOT NULL, expired_time NOT NULL);
CREATE TABLE DEVICE_IDENTITY(id VARCHAR(64) PRIMARY KEY, device_id VARCHAR(16) NOT NULL, jid VARCHAR(32) NOT NULL, credentials VARCHAR(32) NOT NULL, state NOT NULL);
CREATE UNIQUE INDEX UNIQUE_INDEX_DEVICE_ID ON DEVICE_IDENTITY (device_id);
CREATE UNIQUE INDEX UNIQUE_INDEX_JID ON DEVICE_IDENTITY (jid);