CREATE TABLE DEVICE_AUTHORIZATION(id VARCHAR(64) PRIMARY KEY, device_id VARCHAR(16) NOT NULL, authorizer VARCHAR(16) NOT NULL, authorized_time TIMESTAMP NOT NULL, expired_time TIMESTAMP NOT NULL, canceled BOOLEAN DEFAULT FALSE NOT NULL);
CREATE TABLE DEVICE(id VARCHAR(64) PRIMARY KEY, device_id VARCHAR(16) NOT NULL, authorization_id VARCHAR(64), device_name VARCHAR(16) NOT NULL, credentials VARCHAR(16) NOT NULL, mode VARCHAR(16), software_version VARCHAR(16), registration_time TIMESTAMP NOT NULL);
CREATE INDEX INDEX_DEVICE_AUTHORIZATION_DEVICE_ID ON DEVICE_AUTHORIZATION (device_id);
CREATE INDEX INDEX_DEVICE_AUTHORIZATION_AUTHORIZED_TIME ON DEVICE_AUTHORIZATION (authorized_time);
CREATE INDEX INDEX_DEVICE_AUTHORIZATION_EXPIRED_TIME ON DEVICE_AUTHORIZATION (expired_time);
CREATE INDEX INDEX_DEVICE_ID ON DEVICE (device_id);
CREATE INDEX INDEX_DEVICE_NAME ON DEVICE (device_name);
