CREATE TABLE DEVICE_AUTHORIZATIONS(id VARCHAR(64) PRIMARY KEY, device_id VARCHAR(32) NOT NULL, authorizer VARCHAR(64) NOT NULL, authorized_time TIMESTAMP NOT NULL, expired_time TIMESTAMP NOT NULL, canceled BOOLEAN DEFAULT FALSE NOT NULL);
CREATE TABLE DEVICES(id VARCHAR(64) PRIMARY KEY, device_id VARCHAR(32) NOT NULL, mode VARCHAR(16), software_version VARCHAR(16), registration_time TIMESTAMP NOT NULL);
CREATE TABLE DEVICE_IDENTITIES(id VARCHAR(64) PRIMARY KEY, device_id VARCHAR(32) NOT NULL, device_name VARCHAR(32) NOT NULL, credentials VARCHAR(16) NOT NULL)
CREATE INDEX INDEX_DEVICE_AUTHORIZATIONS_DEVICE_ID ON DEVICE_AUTHORIZATIONS (device_id);
CREATE INDEX INDEX_DEVICE_AUTHORIZATIONS_AUTHORIZED_TIME ON DEVICE_AUTHORIZATIONS (authorized_time);
CREATE INDEX INDEX_DEVICE_AUTHORIZATIONS_EXPIRED_TIME ON DEVICE_AUTHORIZATIONS (expired_time);
CREATE UNIQUE INDEX INDEX_DEVICES_DEVICE_ID ON DEVICES (device_id);
CREATE INDEX INDEX_DEVICE_IDENTITIES_DEVICE_NAME ON DEVICE_IDENTITIES (device_name);
